# Generated by Django 4.2.1 on 2023-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
